server:
  port: 8080

spring:
  application:
    name: agents
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    chat:
      options:
        model: qwen3.7-max
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000

# 日志配置
logging:
  level:
    root: INFO
    com.alibaba.cloud.ai: DEBUG
    org.springframework.ai: DEBUG