spring.application.name=webflux-nacos-mcp-server
server.port=17070
### 必须禁用web应用类型
#spring.main.web-application-type=none
### 禁用banner
#spring.main.banner-mode=off
# MCP服务器名称
spring.ai.mcp.server.name=webflux-mcp-server
# 协议类型：STREAMABLE
spring.ai.mcp.server.protocol=streamable
# 服务器版本号
spring.ai.mcp.server.version=1.0.0
# 推荐用于响应式应用
spring.ai.mcp.server.type=async
spring.ai.mcp.server.instructions="This reactive server provides time information tools and resources"
# 请求超时时间
spring.ai.mcp.server.request-timeout=20s
# MCP 端点路径
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
# 保持连接间隔
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s
# 是否禁用 DELETE 方法
spring.ai.mcp.server.streamable-http.disallow-delete=false
# 调试日志
logging.level.io.modelcontextprotocol.client=debug
logging.level.io.modelcontextprotocol.server=debug
logging.level.io.modelcontextprotocol.spec=debug

#mcp 注册到nacos
#spring.ai.alibaba.mcp.nacos.server-addr=nacos-standalone-3.1.1:8848
spring.ai.alibaba.mcp.nacos.server-addr=127.0.0.1:8848
spring.ai.alibaba.mcp.nacos.username=nacos
spring.ai.alibaba.mcp.nacos.password=nacos
spring.ai.alibaba.mcp.nacos.register.enabled=true
## 指定分组名称
spring.ai.alibaba.mcp.nacos.register.service-group=mcp-server
## 指定服务名称
spring.ai.alibaba.mcp.nacos.register.service-name=webflux-mcp-server
