spring:
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: deepseek-v3.2
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications
    alibaba:
      mcp:
        nacos:
          client:
            enabled: true
            streamable:
              connections:
                server1:
                  service-name: webflux-mcp-server
                  version: 1.0.0
            configs:
              server1:
#                namespace: 0908ca08-c382-404c-9d96-37fe1628b183
                server-addr: 127.0.0.1:8848
                username: nacos
                password: nacos

