# Copyright 2024-2025 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.8'

services:

  # Higress AI Cache Use
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: higress-redis
    volumes:
      - /d/docker-data/redis/data:/data
      - ./conf/redis.conf:/etc/redis/redis-stand.conf
    command: redis-server /etc/redis/redis-stand.conf
    networks:
        - spring-ai-alibaba-higress

  higress:
    container_name: spring-ai-alibaba-higress
    pull_policy: always
    tty: true
    restart: unless-stopped
    volumes:
      - /d/docker-data/higress/data:/data
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
    ports:
      - "18001:8001"
      - "18443:8443"
      - "18080:8080"
    networks:
      - spring-ai-alibaba-higress

  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: nacos-standalone-3.1.1
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    volumes:
      - /d/docker-data/nacos3.1.1/standalone-logs/:/home/nacos/logs
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    networks:
      - spring-ai-alibaba-higress

networks:
  spring-ai-alibaba-higress:
    driver: bridge
