version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - ELASTIC_PASSWORD=root # username: elastic
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.14.3
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=root # Must match ELASTIC_PASSWORD for Elasticsearch
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "18001:8001"
    volumes:
      - rddata:/data
    environment:
      TZ: Asia/Shanghai
      # Optional: Set a password for Redis
      # - REDIS_ARGS="--requirepass your_strong_password"
      # Optional: Configure RedisInsight password
      # - REDISINSIGHT_PASSWORD=your_insight_password

  pgvecto-rs:
    image: pgvector/pgvector:pg16 #内置 PostgreSQL 16 + pgvector 插件。
    container_name: pgvector-db
    ports:
      - "5432:5432"
#    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
#      - ./volumes/pgvecto_rs/data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 1s
#      timeout: 3s
#      retries: 30
volumes:
  esdata:
  pgdata:
  rddata: