server:
  port: 19000

spring:
  application:
    name: mcp-gateway-server
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    alibaba:
      mcp:
        # MCP Gateway 配置
        gateway:
          enabled: true
          registry: nacos
          # 配置要发现和聚合的 MCP Server 服务名称
          nacos:
            service-names:
              - sse-sync-mcp-server         # SSE 协议的 MCP Server
              - webflux-sse-mcp-server
        # Nacos 注册中心配置
        nacos:
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
        server: DEBUG